### ISSUE TITLE
Cleanest way to validate a signature

### ISSUE THREAD

**Issue by husseinhere** [mikelodder7/blsful#4]
I'm trying to performance test this library against other libraries in languages I'm more familiar with so I apologize for the newbie question. I wrote this function which works:

```
// all inputs are presented as hex encoded strings
fn validate_signature(pubkey: &str, message: &str, signature: &str) -> bool {
    let pubkey_bytes = hex::decode(pubkey).expect("pub key must be correct");
    let pubkey: PublicKey<Bls12381G2Impl> = serde_bare::from_slice::<PublicKey<Bls12381G2Impl>>(pubkey_bytes.as_slice()).expect("must be able deserialize pubkey");
    let msg = hex::decode(message).expect("failed to decode hex value");

    let mut sig_vector = vec![0; 97]; // a signature is 96 bytes, plus we're going to add a leading 1
    let last_bytes = &mut sig_vector[1..];    

    hex::decode_to_slice(signature, last_bytes).expect("must be valid sig");
    
    let sig = serde_bare::from_slice::<blsful::Signature<Bls12381G2Impl>>(sig_vector.as_slice()).expect("must be able to deserialize sig");
    let valid = sig.verify(&pubkey, msg);

    valid.is_ok()
}
```

I'm just wondering if there's any improvements you can see. I couldn't figure out how to deserialize a "BasicSignature" without the prepending of `0` hack I used there. 

Thanks very much!

**Comment by mikelodder7** [comment]
Yeah you can use the `as_raw_value` to get out the value itself without the leading type byte. Then when you want to get it back you can just use Signature::Basic(point) since the inner value is public. Hope that helps

**Comment by mikelodder7** [comment]
To get the hex string to a point, you can use `from_compressed_hex`

**Comment by mikelodder7** [comment]
For the key you can just use try_from since all structs support it from a slice of bytes

**Comment by mikelodder7** [comment]
Overall you should be able to cut the number of lines down to just 3

**Comment by husseinhere** [comment]
Thanks for the pointers!
