### ISSUE TITLE
Converting bytes into a private key

### ISSUE THREAD

**Issue by husseinhere** [mikelodder7/blsful#5]
Firstly I apologize as this isn't exactly an issue, but a request for help. 

Secondly thanks for your amazing work with your library, it is in some cases is 39x faster than a pure javascript solution that I've been trying to port. 

The only operation I need which I can't figure out to do is how to convert a 40 byte hash as a PrivateKey. In the javascript version it starts with a hash, e.g.

`[202, 109, 60, 56, 243, 94, 234, 17, 222, 103, 73, 119, 83, 36, 172, 68, 181, 27, 66, 32, 61, 12, 118, 192, 255, 103, 26, 98, 247, 20, 156, 130, 140, 217, 185, 187, 43, 215, 139, 219]`

then reads it as a bigint: `1831827922067354517797306176892828000911014916050637590219351031477825861890959663243477624057290`

Then it does `(num % (ORDER - 1)) + 1`
where ORDER is defined as: `52435875175126190479447740508185965837690552500527637822603658699938581184513` aka `0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`  (and the same as MODULUS in blsful)

Which gives a final result of `9867581098058959301707420087865031789140716346047138769054786295276093541340`

thus the private key should be: `[
  220, 139, 215,  43, 196,   7,  64, 103,
   91, 124, 132, 104, 105,  60,  61, 183,
  200,  59, 106, 227,  61, 213, 187, 251,
  112, 208, 101,   3,  93, 218, 208,  21
]`

This operation needs to be done extensively, so I want to make sure I'm doing it in the best way possible rather than something naive like converting it to bignum's and doing maths. 

Thanks!

**Comment by husseinhere** [comment]
I'm able to get close to a solution with:

```
    // I have prepended 8 0's to the vector i'm working with
    let bytes = [0, 0, 0, 0, 0, 0, 0, 0, 202, 109, 60, 56, 243, 94, 234, 17, 222, 103, 73, 119, 83, 36, 172, 68, 181, 27, 66, 32, 61, 12, 118, 192, 255, 103, 26, 98, 247, 20, 156, 130, 140, 217, 185, 187, 43, 215, 139, 219];
    let s = Scalar::from_okm(&bytes);
```

Then when I print  `s` I get a value of `0x15d0da5d0365d070fbbbd53de36a3bc8b73d3c6968847c59a83d39f451713dd2` which is very close to the private key I'm after: `0x15d0da5d0365d070fbbbd53de36a3bc8b73d3c6968847c5b674007c42bd78bdc` but not exactly the same.

So what I'm pretty sure is happening, is `blsful` is doing:

`num % ORDER` to get the private key. While the code I'm trying to be compatible with is doing: `(num % (ORDER - 1)) + 1`

**Comment by mikelodder7** [comment]
You might be encountering the big vs little endian ordering issue. `from_okm` expects big endian which it looks like your expecting. However are your original bytes in that order?

**Comment by mikelodder7** [comment]
Yeah there is no built in method to do the (ORDER - 1) + 1. Not sure why you would do it that way

**Comment by husseinhere** [comment]
> You might be encountering the big vs little endian ordering issue. `from_okm` expects big endian which it looks like your expecting. However are your original bytes in that order?

Yeah, I am pretty sure I have the endianness correct. I think it's all down to the mod issue

> Yeah there is no built in method to do the (ORDER - 1) + 1. Not sure why you would do it that way

Presumably because `0` is not a valid private key, and this removes the (negligible) chance of it happening. I need to retain compatibility in how I derive the private key, so unfortunately I can't change it. Do you have any tips of how I'd do the (ORDER - 1) + 1  reasonably efficiently?

**Comment by mikelodder7** [comment]
Yeah you could use blsful::elliptic_curve::bigint library to do it.

Use bigint::{impl_modulus, modular::constant_mod::*, Encoding, U48}

Hopefully that's enough to get you started.

**Comment by husseinhere** [comment]
I tried this, but `impl_modulus` panics with `modulus must be odd` :(

**Comment by mikelodder7** [comment]
Then you'll have to use the `div_rem` method where the modulus is what you are looking to use.

**Comment by husseinhere** [comment]
Thank you kind sir. That did the trick.
